# Generated by Django 4.0.5 on 2022-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('CarBooked', models.CharField(max_length=200)),
                ('TimeDuration', models.CharField(max_length=200)),
                ('TimeBooked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_username', models.CharField(max_length=200)),
                ('Vehicle_type', models.CharField(max_length=30)),
                ('Number_plate', models.CharField(max_length=20)),
                ('learners', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
