# Generated by Django 4.0.5 on 2022-07-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_members_school_alter_members_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='learners',
            field=models.IntegerField(null=True),
        ),
    ]
