# Generated by Django 4.0.5 on 2022-07-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_car_learners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.members'),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
