# Generated by Django 4.0.5 on 2022-07-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_booking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='learners',
        ),
    ]
