# Generated by Django 4.0.5 on 2022-07-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
