# Generated by Django 4.0.5 on 2022-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_password2_user_password_booking_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Attended',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
