# Generated by Django 4.0.5 on 2022-07-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
    ]
