# Generated by Django 4.0.5 on 2022-07-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('bookdate', models.CharField(max_length=200)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.gender')),
            ],
        ),
    ]
