# Generated by Django 4.0.5 on 2022-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookdate',
            field=models.DateField(),
        ),
    ]
