# Generated by Django 4.0.5 on 2022-07-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisupdate',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Diagnosisupdate',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
