# Generated by Django 4.0.5 on 2022-07-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
