# Generated by Django 4.0.5 on 2022-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='patientid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
