# Generated by Django 4.0.5 on 2022-07-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_book_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='patient',
        ),
    ]
