# Generated by Django 4.0.5 on 2022-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_book_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisupdate',
            name='patient',
        ),
        migrations.AddField(
            model_name='diagnosisupdate',
            name='patientid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
