# Generated by Django 4.0.5 on 2022-07-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_status_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.DeleteModel(
            name='Diagnosisupdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
