# Generated by Django 4.0.5 on 2022-07-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
