# Generated by Django 4.0.5 on 2022-07-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_inquire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.DecimalField(decimal_places=30, max_digits=30)),
            ],
        ),
    ]
