# Generated by Django 4.0.5 on 2022-07-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_decimal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decimal',
        ),
    ]
