# Generated by Django 4.0.5 on 2022-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('B', 'Blazers')], max_length=50, null=True),
        ),
    ]
