# Generated by Django 4.0.5 on 2022-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('B', 'Blazers'), ('D', 'Dresses'), ('G', 'GymWear'), ('JA', 'Jackets'), ('JE', 'Jeans'), ('M', 'Makeups'), ('S', 'Shirts'), ('SH', 'Shoes'), ('O', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
