# Generated by Django 4.0.5 on 2022-08-02 14:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
