# Generated by Django 4.0.5 on 2022-08-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_item_price_alter_order_itemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.item'),
        ),
    ]
