# Generated by Django 4.0.5 on 2022-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_cart_created_at_remove_cart_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
