# Generated by Django 4.0.5 on 2022-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
